[tasks.check-all]
description = "Run all checks"
dependencies = ["clippy", "fmt", "test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--locked"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.test]
command = "cargo"
args = [
  "test",
  "--all-features",
  "--all-targets",
  "--locked",
]