name: CD
permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    name: Publishing ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            dependencies: "libssl-dev libasound2-dev libdbus-1-dev"

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install ${{ matrix.dependencies }}

      - name: Build
        shell: bash
        run: |
          cargo build --locked --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf hullcaster-${{ matrix.target }}.tar.gz hullcaster
          shasum -a 256 hullcaster-${{ matrix.target }}.tar.gz > hullcaster-${{ matrix.target }}.sha256

      - uses: actions/upload-artifact@v4
        with:
          name: hullcaster-${{ matrix.target }}.tar.gz
          path: target/${{ matrix.target }}/release/hullcaster-${{ matrix.target }}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/${{ matrix.target }}/release/hullcaster-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}